#!/bin/bash

echo "=================================="
echo "Convex 설정 가이드"
echo "=================================="
echo ""
echo "터미널에서 다음 명령을 직접 실행해주세요:"
echo ""
echo "1. 프로젝트 디렉토리로 이동:"
echo "   cd \"/Users/gimdaeseong/claude coin\""
echo ""
echo "2. Convex 개발 서버 시작:"
echo "   npx convex dev"
echo ""
echo "3. 프롬프트에서 다음과 같이 선택:"
echo "   - 'Create a new project' 선택"
echo "   - 프로젝트 이름: trading-diary"
echo "   - 팀 선택 (본인 계정)"
echo ""
echo "4. 생성된 Convex URL을 .env.local 파일에 추가"
echo ""
echo "5. 개발 서버 시작:"
echo "   npm run dev"
echo ""
echo "=================================="

# 터미널에서 대화형으로 실행하도록 안내
echo "위 명령들을 터미널에서 대화형으로 실행해주세요."
echo "자동화된 스크립트로는 Convex 설정이 불가능합니다."